Lanelet:
  MAXP: 40                    # max number of points on a road
  MAXPRE: 1                   # max number of preceding roads
  MAXSUC: 1                   # max number of succeeding roads
  MAXL: 3                     # max number of lanes
#
Init:
  Test:
    Lane: 30624
  Ego:
    Lane: 30626